<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SISBLRLPT194" failures="1" tests="10" name="Default test" time="132.0" errors="0" timestamp="16 Jun 2020 14:37:01 GMT">
  <testcase classname="Page_factory.customer" name="login" time="62.406">
    <failure type="java.lang.AssertionError" message="expected [Reports List  ] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Reports List  ] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at Page_factory.customer.login(customer.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="Page_factory.customer" name="createcustomer_contactinfo" time="28.196"/>
  <testcase classname="Page_factory.customer" name="createcustomer_underwritinginfo" time="12.22"/>
  <testcase classname="Page_factory.customer" name="createcustomer_premiumquotes" time="3.039"/>
  <testcase classname="Page_factory.customer" name="createcustomer_wip" time="3.06"/>
  <testcase classname="Page_factory.customer" name="createcustomer_reports" time="3.038"/>
  <testcase classname="Page_factory.customer" name="createcustomer_bondlog" time="3.034"/>
  <testcase classname="Page_factory.customer" name="createcustomer_bidbondlog" time="3.044"/>
  <testcase classname="Page_factory.customer" name="createcustomer_finanalysis" time="3.04"/>
  <testcase classname="Page_factory.customer" name="createcustomer_businesscontact" time="3.042"/>
</testsuite> <!-- Default test -->
